<?php

?>
<html>
<head>

</head>
<body >
 

<div id="wmsdlg_main" style="height:100%;">
    <form id="wmsdlg_form">
        <table width="100%" height="100%">
            <tr height="30px">
                <td width="80%" >
                    <table width="100%">
                        <tr>
                            <td><input type="text" id="wmsdlg_url" name="wmsdlg_url" size="50"/> 
                               <img id="wmsdlg_loadingIndicator" src="images/indicators/ajax-loader-small-arrow.gif" alt="loading" style="display:none">
                            </td>
                            <td width="50px"><input type="button" id="wmsdlg_urlOk" value="OK"/></td>
                        </tr>
                    </table>
                </td>
            </tr>
          
            <tr >
                <td>
                    <table width="100%" height="100%">
                        <tr>
                            <td height="100%" >
                                <div id="wmsdlg_layers" />
                            </td>
                            <td width="150px">
                                <table width="100%" >
                                    <tr>
                                        <td>Image Format<br /><select id="wmsdlg_format" name="wmsdlg_format"/></td>
                                    </tr>  
                                    <tr >
                                        <td>Projection<br /><select id="wmsdlg_srs" name="wmsdlg_srs"/></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
          </tr>
          
          <tr height="30px">
            <td id="wmsdlg_bottom">
                <input type="button" id="wmsdlg_button_ok" value="OK"/>
                <input type="button" id="wmsdlg_button_cancel" value="Cancel" />
            </td>
          </tr>

        </table>
    </form>
</div>   

<script type="text/javascript">
  PM.Plugin.WMSClient.init();
</script>



</body>
</html>