<?php
/******************************************************************************
*
* Purpose: Authentication dmin windows template
* Author:  Walter Lorenzetti, gis3w, lorenzetti@gis3w.it
*
******************************************************************************
*
* Copyright (c) 2008-2010 gis3w
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version. See the COPYING file.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with p.mapper; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*
******************************************************************************/
// prevent XSS
if (isset($_REQUEST['PM_INCPHP'])) exit();

session_start();
require_once($_SESSION['PM_INCPHP'] . "/common.php");
require_once($_SESSION['PM_INCPHP'] . "/globals.php");

// pm_logDebug(3,$_SESSION['PM_PLUGIN_REALPATH'],"Sessione");

?>
<div id="pmAuthId" style="width:100%; height:100%; display:block;">
<div class="ui-layout-north">
  <? echo _p('Config administration pannel'); ?>
</div>
    <div class="ui-layout-west">
      <ul>
        <li>
          <a href="javascript:PM.Plugin.pmAuth.getUsers('view');"><img src="<? echo $_SESSION['PM_PLUGIN_LOCATION'] ?>/pmauth/users.png" alt ="image"/><? echo _p('Users'); ?></a>
        </li>
      </ul>
    </div>
    <div class="ui-layout-center">
      <? echo _p('Here is possibile administrate the user') ?>
    </div>
</div>

<script type="text/javascript">
  PM.Plugin.pmAuth.layout();
</script>