<?php
require_once("incphp/pmsession.php");
require_once("incphp/common.php");
require_once("incphp/globals.php");

header("Content-type: text/html; charset=$defCharset");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $gLanguage ?>" xml:lang="<?php echo $gLanguage ?>">

<head>
 <link rel="stylesheet" href="templates/default.css" type="text/css" />
 <title>p.mapper <?php echo (_p("Help"))?></title>
</head>
<body class="TOOLFRAME">

<h1>p.mapper <?php echo (_p("Help"))?></h1>

</body>
</html>