<?php
/******************************************************************************
 *
 * Purpose: print dialog 
 * Author:  Armin Burger
 *
 ******************************************************************************
 *
 * Copyright (c) 2003-2006 Armin Burger
 *
 * This file is part of p.mapper.
 *
 * p.mapper is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version. See the COPYING file.
 *
 * p.mapper is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with p.mapper; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 ******************************************************************************/
 
require_once("incphp/pmsession.php");
require_once("incphp/common.php");
require_once("incphp/globals.php");
require_once("incphp/print/printxml.php");

$geo_scale0 = round($_SESSION["geo_scale"]);
$geo_scale = number_format(round($geo_scale0, -1 * (strlen($geo_scale0) - 2)), 0, '', '');

$pXml = new PrintXML_HTML("/print/printdlg/*", $geo_scale);
$printHTML = $pXml->xmlToHtml(false, false, false);

header("Content-type: text/html; charset=$defCharset");
?>
<html>
<head>
</head>
<body >
 <form action="printmap.phtml" target="_blank" id="choosescale" method="get" > 
    <?php echo $printHTML ?>
    <div>
        <?php echo ("<input type=\"hidden\" name=\"" . ini_get("session.name") . "\" value=\"" . session_id() . "\" />") ?>
        <input type="hidden" name="config" value="<?php echo $_SESSION['config'] ?>" />
    </div> 
 </form> 
 <script type="text/javascript">
    
 </script>

</body>
</html>