<?php

/** 
 * uncompressed version: scalebar.js 
 * compressed version: scalebar_cjs.js 
 */
$jsFiles = array("scalebar.js");


/** 
 * init function (in scalebar.js) to create scalebar 
 */
$jsInitFunction = "PM.Plugin.ScaleBar.init()";


/**
 * Set scale bar style
 * possible values: ...-fancy.css, -thin.css, -thinner.css, -medium.css -fat.css
 */
$cssFiles = array("scalebar-medium.css");



?>